# Generated by Django 5.0.6 on 2024-06-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.IntegerField()),
                ('email', models.CharField(max_length=99)),
                ('password', models.IntegerField()),
                ('Aadhar', models.IntegerField()),
                ('place', models.CharField(max_length=99)),
                ('initialamount', models.IntegerField()),
            ],
        ),
    ]
