# Generated by Django 5.0.6 on 2024-06-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='username',
            field=models.CharField(default=1, max_length=99),
            preserve_default=False,
        ),
    ]
