# Generated by Django 5.0.6 on 2024-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_place_home_place_home_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='fullname',
            field=models.CharField(max_length=99),
        ),
    ]
